/**
 * Turns an adjustment's CSS filter chain into compositor shader passes.
 *
 * Adjustments are authored as a CSS filter string because the browser applies
 * it on the GPU for free via `ctx.filter`. WebKitGTK — the webview the desktop
 * shell runs on — accepts the property, reads it back, and ignores it, so on
 * desktop every slider in the panel moved nothing. The compositor already runs
 * shader passes per layer, and the effects crate now carries the same colour
 * functions, so the chain is translated into passes instead.
 *
 * The chain is generated by the adjustment definitions, never typed by a user,
 * so parsing only has to handle what those emit. Anything unrecognised is
 * dropped rather than guessed at — a wrong picture is worse than an unapplied
 * slider.
 */

import type { EffectPass } from "@/effects/types";

/** CSS filter functions with a matching shader in the effects crate. */
const SHADER_BY_FUNCTION: Record<string, string> = {
	brightness: "brightness",
	contrast: "contrast",
	saturate: "saturate",
	"hue-rotate": "hue-rotate",
	invert: "invert",
};

/** Values these functions leave the picture untouched at. */
const NEUTRAL_AMOUNT: Record<string, number> = {
	brightness: 1,
	contrast: 1,
	saturate: 1,
	"hue-rotate": 0,
	invert: 0,
};

const FILTER_FUNCTION_PATTERN = /([a-z-]+)\(([^)]*)\)/g;

/**
 * Reads a CSS filter argument. `hue-rotate` is in degrees (`12deg`, `0.2turn`,
 * `0.5rad`); the rest are a bare multiplier or a percentage.
 */
function parseAmount({
	name,
	raw,
}: {
	name: string;
	raw: string;
}): number | null {
	const value = raw.trim();
	if (value.length === 0) return null;

	const match = /^(-?[0-9]*\.?[0-9]+)(%|deg|rad|turn)?$/.exec(value);
	if (!match) return null;

	const magnitude = Number.parseFloat(match[1]);
	if (!Number.isFinite(magnitude)) return null;
	const unit = match[2];

	if (name === "hue-rotate") {
		if (unit === "rad") return (magnitude * 180) / Math.PI;
		if (unit === "turn") return magnitude * 360;
		return magnitude;
	}

	return unit === "%" ? magnitude / 100 : magnitude;
}

export function buildAdjustmentFilterPasses({
	filter,
}: {
	filter: string;
}): EffectPass[] {
	const passes: EffectPass[] = [];
	if (filter.length === 0 || filter === "none") return passes;

	for (const match of filter.matchAll(FILTER_FUNCTION_PATTERN)) {
		const name = match[1];
		const shader = SHADER_BY_FUNCTION[name];
		if (!shader) continue;

		const amount = parseAmount({ name, raw: match[2] });
		if (amount === null) continue;
		// A neutral pass is a full-screen draw that changes nothing; the chain
		// usually omits these already, but a keyframe can land on one.
		if (amount === NEUTRAL_AMOUNT[name]) continue;

		passes.push({ shader, uniforms: { u_amount: amount } });
	}

	return passes;
}
