/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export const applyMaskFeather: (a: any) => [number, number, number];
export const getCompositorCanvas: () => [number, number, number];
export const initCompositor: (a: number, b: number) => [number, number];
export const initializeGpu: () => any;
export const releaseTexture: (a: number, b: number) => [number, number];
export const renderFrame: (a: any) => [number, number];
export const resizeCompositor: (a: number, b: number) => [number, number];
export const uploadTexture: (a: any) => [number, number];
export const uploadVideoFrame: (a: any) => [number, number];
export const applyEffectPasses: (a: any) => [number, number, number];
export const getLastFrameProfile: () => any;
export const TICKS_PER_SECOND: () => number;
export const floorToFrame: (a: any) => any;
export const isFrameAligned: (a: any) => number;
export const lastFrameTime: (a: any) => any;
export const mediaTimeAdd: (a: any) => any;
export const mediaTimeClamp: (a: any) => any;
export const mediaTimeFromFrame: (a: any) => any;
export const mediaTimeFromSeconds: (a: any) => any;
export const mediaTimeMax: (a: any) => any;
export const mediaTimeMin: (a: any) => any;
export const mediaTimeSub: (a: any) => any;
export const mediaTimeToFrame: (a: any) => [number, bigint];
export const mediaTimeToSeconds: (a: any) => number;
export const roundToFrame: (a: any) => any;
export const snappedSeekTime: (a: any) => any;
export const formatTimecode: (a: any) => [number, number];
export const guessTimecodeFormat: (a: any) => any;
export const parseTimecode: (a: any) => any;
export const wasm_bindgen_a17a0801410087af___convert__closures_____invoke___wasm_bindgen_a17a0801410087af___JsValue__core_7d5f0a2ba6a62c33___result__Result_____wasm_bindgen_a17a0801410087af___JsError___true_: (a: number, b: number, c: any) => [number, number];
export const wasm_bindgen_a17a0801410087af___convert__closures_____invoke___js_sys_66a37e87208129a3___Function_fn_wasm_bindgen_a17a0801410087af___JsValue_____wasm_bindgen_a17a0801410087af___sys__Undefined___js_sys_66a37e87208129a3___Function_fn_wasm_bindgen_a17a0801410087af___JsValue_____wasm_bindgen_a17a0801410087af___sys__Undefined_______true_: (a: number, b: number, c: any, d: any) => void;
export const wasm_bindgen_a17a0801410087af___convert__closures_____invoke___wasm_bindgen_a17a0801410087af___JsValue______true_: (a: number, b: number, c: any) => void;
export const __wbindgen_malloc: (a: number, b: number) => number;
export const __wbindgen_realloc: (a: number, b: number, c: number, d: number) => number;
export const __wbindgen_exn_store: (a: number) => void;
export const __externref_table_alloc: () => number;
export const __wbindgen_externrefs: WebAssembly.Table;
export const __wbindgen_free: (a: number, b: number, c: number) => void;
export const __wbindgen_destroy_closure: (a: number, b: number) => void;
export const __externref_table_dealloc: (a: number) => void;
export const __wbindgen_start: () => void;
