//! Turns an adjustment's CSS filter chain into compositor shader passes —
//! `apps/web/src/adjustments/filter-passes.ts`.
//!
//! Adjustments are authored as a CSS filter string because the browser applies
//! it on the GPU for free via `ctx.filter`. WebKitGTK — the webview the desktop
//! shell runs on — accepts the property, reads it back, and ignores it, so on
//! desktop every slider in the panel moved nothing. The compositor already runs
//! shader passes per layer and the effects crate carries the same colour
//! functions, so the chain is translated into passes instead.
//!
//! The chain is generated by the adjustment definitions, never typed by a
//! user, so parsing only has to handle what those emit. Anything unrecognised
//! is dropped rather than guessed at — a wrong picture is worse than an
//! unapplied slider.
//!
//! The TypeScript did this with two regular expressions. They are written out
//! by hand here rather than pulling `regex` into the wasm bundle for two
//! patterns whose whole grammar is a name, a paren and a number.

use std::collections::HashMap;

use bridge::export;
use serde::{Deserialize, Serialize};

/// CSS filter functions with a matching shader in the effects crate, paired
/// with the value each one leaves the picture untouched at.
const FILTER_FUNCTIONS: [(&str, &str, f64); 5] = [
    ("brightness", "brightness", 1.0),
    ("contrast", "contrast", 1.0),
    ("saturate", "saturate", 1.0),
    ("hue-rotate", "hue-rotate", 0.0),
    ("invert", "invert", 0.0),
];

/// One compositor pass: a shader and the uniforms it reads. Only `u_amount` is
/// ever set from a filter chain, but the shape is the compositor's.
#[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "wasm", tsify(into_wasm_abi, hashmap_as_object))]
#[derive(Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AdjustmentFilterPass {
    pub shader: String,
    pub uniforms: HashMap<String, f64>,
}

/// The chain's passes, in the order the filter wrote them.
#[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "wasm", tsify(into_wasm_abi, hashmap_as_object))]
#[derive(Serialize, Clone, Debug, PartialEq)]
#[serde(rename_all = "camelCase")]
pub struct AdjustmentFilterPassList {
    pub passes: Vec<AdjustmentFilterPass>,
}

fn is_name_character(character: char) -> bool {
    character.is_ascii_lowercase() || character == '-'
}

/// Every `name(argument)` in the string, in order.
///
/// Stands in for `/([a-z-]+)\(([^)]*)\)/g`: a run of name characters, an open
/// paren, and everything up to the next close paren. A run not followed by a
/// paren, or a paren never closed, matches nothing — the same as the regex.
fn filter_functions(filter: &str) -> Vec<(String, String)> {
    let characters: Vec<char> = filter.chars().collect();
    let mut found = Vec::new();
    let mut index = 0;

    while index < characters.len() {
        if !is_name_character(characters[index]) {
            index += 1;
            continue;
        }

        let name_start = index;
        while index < characters.len() && is_name_character(characters[index]) {
            index += 1;
        }
        if index >= characters.len() || characters[index] != '(' {
            continue;
        }

        let argument_start = index + 1;
        let Some(offset) = characters[argument_start..].iter().position(|c| *c == ')') else {
            // Unclosed: the regex would not match here or anywhere after it.
            break;
        };
        let argument_end = argument_start + offset;
        found.push((
            characters[name_start..index].iter().collect::<String>(),
            characters[argument_start..argument_end].iter().collect::<String>(),
        ));
        index = argument_end + 1;
    }

    found
}

/// Whether `text` is `-?[0-9]*\.?[0-9]+` — the number grammar the chain emits.
/// Notably `"1."` is not a number and `".5"` is.
fn is_filter_number(text: &str) -> bool {
    let digits = text.strip_prefix('-').unwrap_or(text);
    let (whole, fraction) = match digits.split_once('.') {
        Some((whole, fraction)) => (whole, Some(fraction)),
        None => (digits, None),
    };
    if !whole.chars().all(|character| character.is_ascii_digit()) {
        return false;
    }
    match fraction {
        // A decimal point has to be followed by at least one digit, and by
        // nothing that is not a digit — `1.2.3` is not a number.
        Some(fraction) => {
            !fraction.is_empty() && fraction.chars().all(|character| character.is_ascii_digit())
        }
        None => !whole.is_empty(),
    }
}

/// Reads a CSS filter argument. `hue-rotate` is in degrees (`12deg`,
/// `0.2turn`, `0.5rad`); the rest are a bare multiplier or a percentage.
fn parse_amount(name: &str, raw: &str) -> Option<f64> {
    let value = raw.trim();
    if value.is_empty() {
        return None;
    }

    let (number, unit) = ["%", "deg", "rad", "turn"]
        .into_iter()
        .find_map(|unit| value.strip_suffix(unit).map(|number| (number, Some(unit))))
        .unwrap_or((value, None));
    if !is_filter_number(number) {
        return None;
    }
    // Rust's float parser rejects a leading `.`, which `parseFloat` accepts.
    let normalised = match number.strip_prefix('-') {
        Some(rest) if rest.starts_with('.') => format!("-0{rest}"),
        _ if number.starts_with('.') => format!("0{number}"),
        _ => number.to_string(),
    };
    let magnitude: f64 = normalised.parse().ok()?;
    if !magnitude.is_finite() {
        return None;
    }

    if name == "hue-rotate" {
        return Some(match unit {
            Some("rad") => (magnitude * 180.0) / std::f64::consts::PI,
            Some("turn") => magnitude * 360.0,
            _ => magnitude,
        });
    }

    Some(if unit == Some("%") {
        magnitude / 100.0
    } else {
        magnitude
    })
}

/// The passes a filter chain becomes. An empty chain, `none`, an unknown
/// function, an unreadable argument and a neutral amount all contribute
/// nothing.
pub fn build_adjustment_filter_passes(filter: &str) -> Vec<AdjustmentFilterPass> {
    let mut passes = Vec::new();
    if filter.is_empty() || filter == "none" {
        return passes;
    }

    for (name, argument) in filter_functions(filter) {
        let Some((_, shader, neutral)) = FILTER_FUNCTIONS
            .into_iter()
            .find(|(function, _, _)| *function == name)
        else {
            continue;
        };
        let Some(amount) = parse_amount(&name, &argument) else {
            continue;
        };
        // A neutral pass is a full-screen draw that changes nothing; the chain
        // usually omits these already, but a keyframe can land on one.
        if amount == neutral {
            continue;
        }

        passes.push(AdjustmentFilterPass {
            shader: shader.to_string(),
            uniforms: HashMap::from([("u_amount".to_string(), amount)]),
        });
    }

    passes
}

// Bridge surface.

#[cfg_attr(feature = "wasm", derive(tsify_next::Tsify))]
#[cfg_attr(feature = "wasm", tsify(from_wasm_abi, hashmap_as_object))]
#[derive(Deserialize, Clone, Debug)]
#[serde(rename_all = "camelCase")]
pub struct BuildAdjustmentFilterPassesOptions {
    pub filter: String,
}

#[export]
pub fn build_adjustment_filter_passes_value(
    BuildAdjustmentFilterPassesOptions { filter }: BuildAdjustmentFilterPassesOptions,
) -> AdjustmentFilterPassList {
    AdjustmentFilterPassList {
        passes: build_adjustment_filter_passes(&filter),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn amounts(filter: &str) -> Vec<(String, f64)> {
        build_adjustment_filter_passes(filter)
            .into_iter()
            .map(|pass| (pass.shader, pass.uniforms["u_amount"]))
            .collect()
    }

    #[test]
    fn a_chain_becomes_one_pass_per_function_in_order() {
        assert_eq!(
            amounts("brightness(1.2) contrast(0.8) saturate(1.5)"),
            vec![
                ("brightness".to_string(), 1.2),
                ("contrast".to_string(), 0.8),
                ("saturate".to_string(), 1.5),
            ],
        );
    }

    #[test]
    fn an_empty_chain_draws_nothing() {
        assert!(build_adjustment_filter_passes("").is_empty());
        assert!(build_adjustment_filter_passes("none").is_empty());
    }

    #[test]
    fn a_function_with_no_shader_is_dropped_rather_than_guessed_at() {
        // `blur` has no colour shader; the pass is skipped and the ones around
        // it still land.
        assert_eq!(
            amounts("blur(4px) invert(0.5)"),
            vec![("invert".to_string(), 0.5)],
        );
    }

    #[test]
    fn a_neutral_amount_contributes_no_pass() {
        assert!(build_adjustment_filter_passes("brightness(1)").is_empty());
        assert!(build_adjustment_filter_passes("hue-rotate(0deg)").is_empty());
        assert_eq!(
            amounts("brightness(1) contrast(1.1)"),
            vec![("contrast".to_string(), 1.1)],
        );
    }

    #[test]
    fn a_percentage_is_a_hundredth_of_a_multiplier() {
        assert_eq!(amounts("saturate(150%)"), vec![("saturate".to_string(), 1.5)]);
        assert!(build_adjustment_filter_passes("saturate(100%)").is_empty());
    }

    #[test]
    fn hue_rotation_reaches_the_shader_in_degrees() {
        assert_eq!(
            amounts("hue-rotate(45deg)"),
            vec![("hue-rotate".to_string(), 45.0)],
        );
        assert_eq!(
            amounts("hue-rotate(0.5turn)"),
            vec![("hue-rotate".to_string(), 180.0)],
        );
        let radians = amounts("hue-rotate(1rad)");
        assert!((radians[0].1 - 57.295_779_513_082_32).abs() < 1e-9);
        // A bare number is already degrees, unlike the multiplier functions
        // where a bare number is a ratio.
        assert_eq!(
            amounts("hue-rotate(90)"),
            vec![("hue-rotate".to_string(), 90.0)],
        );
    }

    #[test]
    fn a_leading_decimal_point_parses_the_way_parse_float_does() {
        assert_eq!(amounts("invert(.25)"), vec![("invert".to_string(), 0.25)]);
        assert_eq!(
            amounts("brightness(-.5)"),
            vec![("brightness".to_string(), -0.5)],
        );
    }

    #[test]
    fn an_unreadable_argument_drops_its_pass() {
        assert!(build_adjustment_filter_passes("brightness()").is_empty());
        assert!(build_adjustment_filter_passes("brightness(   )").is_empty());
        assert!(build_adjustment_filter_passes("brightness(1.2.3)").is_empty());
        assert!(build_adjustment_filter_passes("brightness(1.)").is_empty());
        assert!(build_adjustment_filter_passes("brightness(abc)").is_empty());
        assert!(build_adjustment_filter_passes("brightness(1px)").is_empty());
    }

    #[test]
    fn an_unclosed_function_ends_the_chain() {
        // The regex this replaces cannot match past a paren that never closes,
        // and neither can anything after it.
        assert_eq!(
            amounts("invert(0.5) contrast(2"),
            vec![("invert".to_string(), 0.5)],
        );
    }

    #[test]
    fn whitespace_around_an_argument_is_ignored() {
        assert_eq!(
            amounts("brightness( 1.2 )"),
            vec![("brightness".to_string(), 1.2)],
        );
    }

    #[test]
    fn a_name_that_is_not_followed_by_a_paren_matches_nothing() {
        assert!(build_adjustment_filter_passes("brightness 1.2").is_empty());
        // …and does not stop the scan: the next real function still lands.
        assert_eq!(
            amounts("brightness 1.2 invert(1)"),
            vec![("invert".to_string(), 1.0)],
        );
    }
}
