/**
 * Applies a CSS filter chain on engines where `ctx.filter` does nothing.
 *
 * WebKitGTK — the webview behind the desktop shell — accepts the property,
 * parses it, reads it back, and then ignores it at draw time. Adjustments
 * already route around that by handing their chain to the compositor as shader
 * passes (see `adjustments/filter-passes.ts`), but effects cannot: a shader pass
 * runs on the finished layer quad, while an effect like Glow needs its blurred
 * copy *composited back over the original* mid-paint. So the chain is applied
 * here instead, on the canvas, using only operations WebKitGTK does implement.
 *
 * Two mechanisms cover everything the bundled effects emit:
 *
 * - **Blur** is a three-pass box cascade on a reduced copy of the frame. The
 *   cascade is the standard Gaussian approximation and, run as a sliding window,
 *   costs the same whatever the radius; shrinking first is what keeps the pixel
 *   count small, and the shrink is itself part of the blur, so the cascade is
 *   only asked for the remainder. An earlier attempt used the resampling alone,
 *   which was cheaper but quantised badly — radius 5 and radius 10 came out
 *   identical, so the slider had dead stretches.
 * - **The colour functions** fold into one pass over the pixels: brightness,
 *   contrast and invert collapse into a single 256-entry lookup table, and
 *   saturate into a luma mix applied alongside it. The whole chain therefore
 *   costs one read-modify-write however many functions it names.
 *
 * The chain is generated by the effect definitions, never typed by a user, so
 * parsing only handles what those emit. Anything unrecognised is skipped rather
 * than guessed at.
 */

import { supportsCanvasFilter } from "./canvas-filter-support";
import { borrowSurface, SURFACE_KEYS, type Surface } from "./surface-pool";

type ColorOp =
	| { kind: "brightness"; amount: number }
	| { kind: "contrast"; amount: number }
	| { kind: "saturate"; amount: number }
	| { kind: "invert"; amount: number };

type FilterOp = ColorOp | { kind: "blur"; radius: number };

const FILTER_FUNCTION_PATTERN = /([a-z-]+)\(([^)]*)\)/g;

/**
 * Reads one filter argument. Blur is a pixel length; the colour functions take a
 * bare multiplier or a percentage.
 */
function parseArgument({ name, raw }: { name: string; raw: string }): number | null {
	const match = /^(-?[0-9]*\.?[0-9]+)(%|px)?$/.exec(raw.trim());
	if (!match) return null;

	const magnitude = Number.parseFloat(match[1]);
	if (!Number.isFinite(magnitude)) return null;

	if (name === "blur") return match[2] === "px" || !match[2] ? magnitude : null;
	return match[2] === "%" ? magnitude / 100 : magnitude;
}

function parseFilterChain({ filter }: { filter: string }): FilterOp[] {
	const ops: FilterOp[] = [];
	if (filter.length === 0 || filter === "none") return ops;

	for (const match of filter.matchAll(FILTER_FUNCTION_PATTERN)) {
		const name = match[1];
		const amount = parseArgument({ name, raw: match[2] });
		if (amount === null) continue;

		switch (name) {
			case "blur":
				if (amount > 0.5) ops.push({ kind: "blur", radius: amount });
				break;
			case "brightness":
			case "contrast":
			case "saturate":
				if (amount !== 1) ops.push({ kind: name, amount });
				break;
			case "invert":
				if (amount !== 0) ops.push({ kind: "invert", amount });
				break;
			default:
				break;
		}
	}

	return ops;
}

/**
 * The hardest a single `drawImage` may shrink. Bilinear sampling reads a 2x2
 * neighbourhood, so halving is the most that still touches every source pixel —
 * shrinking to a thirtieth in one draw samples a scattering of them and the
 * result comes back as a blocky mosaic. Bigger reductions are reached by
 * halving repeatedly.
 */
const MAX_SHRINK_PER_STEP = 0.5;

/**
 * How much standard deviation a shrink-and-stretch round trip contributes per
 * pixel of the shrunken copy: the reduction averages a box that wide and the
 * enlargement convolves it with a bilinear tent of the same width, and the two
 * in quadrature come to about half of it. The box cascade below is asked for
 * whatever is left over rather than for the whole radius.
 */
const RESAMPLE_SIGMA_PER_PIXEL = 0.5;

/** Three box passes is where the cascade stops being visibly boxy. */
const BOX_PASSES = 3;

/** Sigma below this is finer than the source grid; the resample covers it. */
const MIN_BOX_SIGMA = 0.05;

/**
 * Source pixels of radius per unit of shrink. Chosen so the cascade is always
 * left about 1.15 sigma to apply — see `blurSurfaceInPlace`.
 */
const RADIUS_PER_SHRINK = 1.2;

/** The most the cascade will ever run over, in pixels. */
const MAX_CASCADE_PIXELS = 150_000;

/** Past this the shrunken copy is too coarse to hold the frame's shape. */
const MAX_SHRINK = 32;

/**
 * The box widths whose `passes`-fold cascade best matches a Gaussian of
 * `sigma`, by the standard fit: three uniform averages already approximate a
 * Gaussian to within a couple of percent, and picking the two nearest odd widths
 * and splitting the passes between them removes the quantisation that using one
 * rounded width would leave. Returns half-widths.
 */
function boxRadiiForGaussian({
	sigma,
	passes,
}: {
	sigma: number;
	passes: number;
}): number[] {
	const idealWidth = Math.sqrt((12 * sigma * sigma) / passes + 1);
	let lower = Math.floor(idealWidth);
	if (lower % 2 === 0) lower -= 1;
	lower = Math.max(1, lower);
	const upper = lower + 2;
	const split = Math.round(
		(12 * sigma * sigma -
			passes * lower * lower -
			4 * passes * lower -
			3 * passes) /
			(-4 * lower - 4),
	);

	return Array.from({ length: passes }, (_, pass) =>
		((pass < split ? lower : upper) - 1) / 2,
	);
}

/**
 * One separable box pass over premultiplied RGBA, as a sliding window: each step
 * adds the pixel entering the window and drops the one leaving, so the cost is
 * the same whether the box is three pixels wide or three hundred. Edges clamp,
 * which is what keeps a blurred frame from darkening towards its border.
 */
function boxPass({
	input,
	output,
	width,
	height,
	radius,
	stride,
}: {
	input: Float32Array;
	output: Float32Array;
	width: number;
	height: number;
	radius: number;
	/** 1 to sweep along rows, `width` to sweep down columns. */
	stride: number;
}): void {
	const lineLength = stride === 1 ? width : height;
	const lineCount = stride === 1 ? height : width;
	const lineStep = stride === 1 ? width : 1;
	const reach = Math.min(radius, lineLength - 1);
	const window = 2 * reach + 1;

	for (let line = 0; line < lineCount; line += 1) {
		const start = line * lineStep * 4;
		const step = stride * 4;

		let sumR = 0;
		let sumG = 0;
		let sumB = 0;
		let sumA = 0;
		for (let offset = -reach; offset <= reach; offset += 1) {
			const index = start + Math.min(lineLength - 1, Math.max(0, offset)) * step;
			sumR += input[index];
			sumG += input[index + 1];
			sumB += input[index + 2];
			sumA += input[index + 3];
		}

		for (let position = 0; position < lineLength; position += 1) {
			const index = start + position * step;
			output[index] = sumR / window;
			output[index + 1] = sumG / window;
			output[index + 2] = sumB / window;
			output[index + 3] = sumA / window;

			const leaving =
				start + Math.min(lineLength - 1, Math.max(0, position - reach)) * step;
			const entering =
				start +
				Math.min(lineLength - 1, Math.max(0, position + reach + 1)) * step;
			sumR += input[entering] - input[leaving];
			sumG += input[entering + 1] - input[leaving + 1];
			sumB += input[entering + 2] - input[leaving + 2];
			sumA += input[entering + 3] - input[leaving + 3];
		}
	}
}

/**
 * The cascade's two working buffers, kept between frames.
 *
 * At the sizes involved these are a few megabytes a call, and an animated effect
 * calls this on every tick — allocating fresh ones each time is enough garbage
 * to show as periodic stutter. They are grown to the largest size asked for and
 * used as a prefix thereafter, so a small layer borrows the big one rather than
 * causing it to be reallocated.
 */
let blurBuffers: [Float32Array, Float32Array] | null = null;

function borrowBlurBuffers({
	count,
}: {
	count: number;
}): [Float32Array, Float32Array] {
	if (!blurBuffers || blurBuffers[0].length < count) {
		blurBuffers = [new Float32Array(count), new Float32Array(count)];
	}
	return blurBuffers;
}

/**
 * Gaussian-blurs an `ImageData` in place.
 *
 * The channels are premultiplied first. Blurring straight alpha mixes the colour
 * of pixels that are not there, which shows up as a dark or coloured halo around
 * anything with a soft edge — a sticker, a line of text, a keyed subject.
 */
function blurImageData({
	image,
	width,
	height,
	sigma,
}: {
	image: ImageData;
	width: number;
	height: number;
	sigma: number;
}): void {
	const pixels = image.data;
	const count = width * height * 4;
	const [front, scratch] = borrowBlurBuffers({ count });

	for (let index = 0; index < count; index += 4) {
		const alpha = pixels[index + 3] / 255;
		front[index] = pixels[index] * alpha;
		front[index + 1] = pixels[index + 1] * alpha;
		front[index + 2] = pixels[index + 2] * alpha;
		front[index + 3] = pixels[index + 3];
	}

	for (const radius of boxRadiiForGaussian({ sigma, passes: BOX_PASSES })) {
		if (radius < 0.5) continue;
		const whole = Math.round(radius);
		boxPass({
			input: front,
			output: scratch,
			width,
			height,
			radius: whole,
			stride: 1,
		});
		boxPass({
			input: scratch,
			output: front,
			width,
			height,
			radius: whole,
			stride: width,
		});
	}

	for (let index = 0; index < count; index += 4) {
		const alpha = front[index + 3];
		const scale = alpha > 0 ? 255 / alpha : 0;
		pixels[index] = front[index] * scale;
		pixels[index + 1] = front[index + 1] * scale;
		pixels[index + 2] = front[index + 2] * scale;
		pixels[index + 3] = alpha;
	}
}

/**
 * Shrinks `source` to the given size, halving at a time so no step skips source
 * pixels, and returns the canvas holding it.
 */
function shrinkTo({
	source,
	width,
	height,
	targetWidth,
	targetHeight,
}: {
	source: OffscreenCanvas;
	width: number;
	height: number;
	targetWidth: number;
	targetHeight: number;
}): Surface {
	const keys = [SURFACE_KEYS.filterBlur, `${SURFACE_KEYS.filterBlur}-b`];
	let current: OffscreenCanvas = source;
	let currentWidth = width;
	let currentHeight = height;
	let step = 0;
	let surface: Surface | null = null;

	do {
		currentWidth = Math.max(
			targetWidth,
			Math.round(currentWidth * MAX_SHRINK_PER_STEP),
		);
		currentHeight = Math.max(
			targetHeight,
			Math.round(currentHeight * MAX_SHRINK_PER_STEP),
		);
		surface = borrowSurface({
			key: keys[step % keys.length],
			width: currentWidth,
			height: currentHeight,
			// The last one down is the buffer the box cascade reads back.
			readFrequently: currentWidth === targetWidth && currentHeight === targetHeight,
		});
		surface.ctx.imageSmoothingEnabled = true;
		surface.ctx.imageSmoothingQuality = "high";
		surface.ctx.drawImage(current, 0, 0, currentWidth, currentHeight);
		current = surface.canvas;
		step += 1;
	} while (currentWidth > targetWidth || currentHeight > targetHeight);

	return surface;
}

/**
 * Blurs `surface` in place.
 *
 * The work happens on a reduced copy: a blur has no detail finer than its own
 * radius to preserve, so carrying full resolution through the cascade would cost
 * a hundred times the pixels to produce the same picture. The reduction is
 * itself part of the blur, and the cascade is asked only for the remainder.
 */
function blurSurfaceInPlace({
	surface,
	width,
	height,
	radius,
}: {
	surface: Surface;
	width: number;
	height: number;
	radius: number;
}): void {
	// How hard to shrink is a compromise between two failures. Shrink too little
	// and the cascade carries a full-resolution frame, which is the one thing
	// here that costs real time. Shrink too much and the sigma left for the
	// cascade drops below a box width, the fit rounds every pass to nothing, and
	// the blur silently collapses to whatever the resampling happened to give —
	// which is how radius 20 once came out weaker than radius 10.
	//
	// `RADIUS_PER_SHRINK` is set to leave the cascade about 1.15 sigma whatever
	// the radius: comfortably above the rounding floor, and small enough that the
	// resampling still does most of the work.
	const shrinkForRadius = Math.floor(radius / RADIUS_PER_SHRINK);
	// Whatever the radius, the cascade never sees more than a budget of pixels;
	// on a small layer this is 1 and quality is kept where it is free anyway.
	const shrinkForBudget = Math.ceil(
		Math.sqrt((width * height) / MAX_CASCADE_PIXELS),
	);
	const shrink = Math.min(
		MAX_SHRINK,
		Math.max(1, shrinkForRadius, shrinkForBudget),
	);
	const bufferWidth = Math.max(1, Math.round(width / shrink));
	const bufferHeight = Math.max(1, Math.round(height / shrink));

	const buffer =
		shrink > 1
			? shrinkTo({
					source: surface.canvas,
					width,
					height,
					targetWidth: bufferWidth,
					targetHeight: bufferHeight,
				})
			: surface;

	const resampleSigma = shrink > 1 ? RESAMPLE_SIGMA_PER_PIXEL * shrink : 0;
	const remaining =
		Math.sqrt(Math.max(0, radius * radius - resampleSigma * resampleSigma)) /
		shrink;

	if (remaining > MIN_BOX_SIGMA) {
		const image = buffer.ctx.getImageData(0, 0, bufferWidth, bufferHeight);
		blurImageData({
			image,
			width: bufferWidth,
			height: bufferHeight,
			sigma: remaining,
		});
		buffer.ctx.putImageData(image, 0, 0);
	}

	if (buffer === surface) return;

	surface.ctx.save();
	surface.ctx.globalCompositeOperation = "copy";
	surface.ctx.imageSmoothingEnabled = true;
	surface.ctx.imageSmoothingQuality = "high";
	surface.ctx.drawImage(buffer.canvas, 0, 0, width, height);
	surface.ctx.restore();
}

/** The 0..255 lookup table for the brightness/contrast/invert part of a chain. */
function buildChannelLut({ ops }: { ops: ColorOp[] }): Uint8ClampedArray {
	const lut = new Uint8ClampedArray(256);
	for (let value = 0; value < 256; value += 1) {
		let channel = value / 255;
		for (const op of ops) {
			switch (op.kind) {
				case "brightness":
					channel *= op.amount;
					break;
				case "contrast":
					channel = (channel - 0.5) * op.amount + 0.5;
					break;
				case "invert":
					channel = channel * (1 - op.amount) + (1 - channel) * op.amount;
					break;
				case "saturate":
					// Saturation mixes the channels together, so it cannot live in a
					// per-channel table; it is applied alongside one.
					break;
			}
		}
		lut[value] = Math.round(Math.min(1, Math.max(0, channel)) * 255);
	}
	return lut;
}

/** Rec. 601 luma, the weighting the CSS `saturate` filter is defined against. */
function luma({
	red,
	green,
	blue,
}: {
	red: number;
	green: number;
	blue: number;
}): number {
	return 0.213 * red + 0.715 * green + 0.072 * blue;
}

/**
 * Applies the colour half of a chain to `surface`, in place.
 *
 * Order is preserved by construction: the per-channel functions fold into one
 * table in the order they were written, and saturate — the only one that mixes
 * channels — is applied at the position it appears relative to them.
 */
function applyColorOpsInPlace({
	surface,
	width,
	height,
	ops,
}: {
	surface: Surface;
	width: number;
	height: number;
	ops: ColorOp[];
}): void {
	const saturateAmount = ops.reduce(
		(product, op) => (op.kind === "saturate" ? product * op.amount : product),
		1,
	);
	const channelOps = ops.filter((op) => op.kind !== "saturate");
	const lut = channelOps.length > 0 ? buildChannelLut({ ops: channelOps }) : null;
	if (!lut && saturateAmount === 1) return;

	const image = surface.ctx.getImageData(0, 0, width, height);
	const pixels = image.data;

	for (let index = 0; index < pixels.length; index += 4) {
		let red = pixels[index];
		let green = pixels[index + 1];
		let blue = pixels[index + 2];

		if (lut) {
			red = lut[red];
			green = lut[green];
			blue = lut[blue];
		}

		if (saturateAmount !== 1) {
			const grey = luma({ red, green, blue });
			red = grey + (red - grey) * saturateAmount;
			green = grey + (green - grey) * saturateAmount;
			blue = grey + (blue - grey) * saturateAmount;
		}

		pixels[index] = red;
		pixels[index + 1] = green;
		pixels[index + 2] = blue;
	}

	surface.ctx.putImageData(image, 0, 0);
}

/**
 * Runs `filter` over `source` and returns a canvas holding the result, or the
 * source untouched when the chain is empty.
 *
 * The returned canvas is pooled and is only valid until the next call, so the
 * caller must draw it before filtering anything else.
 */
function filterToSurface({
	source,
	width,
	height,
	filter,
}: {
	source: CanvasImageSource;
	width: number;
	height: number;
	filter: string;
}): CanvasImageSource {
	const ops = parseFilterChain({ filter });
	if (ops.length === 0) return source;

	// Only the colour pass reads this surface back, and only it should ask for
	// `willReadFrequently`: that flag moves the canvas off the GPU, which turns
	// the two full-size draws around a blur into CPU blits and cost more than the
	// blur itself. The blur's own read happens on the shrunken buffer instead.
	const readFrequently = ops.some((op) => op.kind !== "blur");
	const surface = borrowSurface({
		key: SURFACE_KEYS.filter,
		width,
		height,
		readFrequently,
	});
	surface.ctx.drawImage(source, 0, 0, width, height);

	// Applied in written order: `brightness(2) blur(4)` and `blur(4) brightness(2)`
	// are different pictures, so the colour runs are flushed around each blur
	// rather than hoisted into one pass at the end.
	let pendingColorOps: ColorOp[] = [];
	const flushColorOps = () => {
		if (pendingColorOps.length === 0) return;
		applyColorOpsInPlace({ surface, width, height, ops: pendingColorOps });
		pendingColorOps = [];
	};

	for (const op of ops) {
		if (op.kind === "blur") {
			flushColorOps();
			blurSurfaceInPlace({ surface, width, height, radius: op.radius });
		} else {
			pendingColorOps.push(op);
		}
	}
	flushColorOps();

	return surface.canvas;
}

/**
 * The source a draw should use to honour `filter` on this engine: the source
 * itself where `ctx.filter` works, and a pre-filtered copy where it does not.
 *
 * Callers keep setting `ctx.filter` as well — on a working engine that is what
 * applies the chain, and on a broken one it is inert, so the same code is
 * correct either way.
 */
export function resolveFilteredSource({
	source,
	width,
	height,
	filter,
}: {
	source: CanvasImageSource;
	width: number;
	height: number;
	filter: string;
}): { source: CanvasImageSource; filter: string } {
	if (filter === "none" || filter.length === 0 || supportsCanvasFilter()) {
		return { source, filter };
	}
	return {
		source: filterToSurface({ source, width, height, filter }),
		filter: "none",
	};
}
